#!/usr/bin/env bash

current_branch="$(git rev-parse --abbrev-ref HEAD)"
printf "current branch: $current_branch\n\n"

if [[ $1 == "publish" ]]; then
    version=$2
    version_msg=$3
    pub get
    flutter clean
    flutter format .
    git add -A
    git commit -m $version_msg
    git tag -a v$version -m $version_msg
    echo "Pushing the version $version to the remote repository."
    git push --tags
    pub publish
else
    echo "If publishing use:"
    echo "  wiz publish <version> <message>"
fi
